version: "3"

services:
  mercure:
    image: dunglas/mercure
    ports:
      - 8080:80
    environment:
      - JWT_KEY=!ChangeMe!
      - DEMO=1
      - ALLOW_ANONYMOUS=1
      - CORS_ALLOWED_ORIGINS=*
      - PUBLISH_ALLOWED_ORIGINS=http://localhost:3000
