version: "3.6"

services:
  reverse-proxy:
    image: traefik:v2.2
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  client-web:
    build:
      context: ./client-web
    labels:
      - "traefik.http.routers.client-web.rule=Host(`reqrdo.localhost`)"
